// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package command

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateCampsiteHandler creates a new instance of MockCreateCampsiteHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCampsiteHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCampsiteHandler {
	mock := &MockCreateCampsiteHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateCampsiteHandler is an autogenerated mock type for the CreateCampsiteHandler type
type MockCreateCampsiteHandler struct {
	mock.Mock
}

type MockCreateCampsiteHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateCampsiteHandler) EXPECT() *MockCreateCampsiteHandler_Expecter {
	return &MockCreateCampsiteHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockCreateCampsiteHandler
func (_mock *MockCreateCampsiteHandler) Handle(ctx context.Context, cmd CreateCampsite) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateCampsite) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreateCampsiteHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockCreateCampsiteHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd CreateCampsite
func (_e *MockCreateCampsiteHandler_Expecter) Handle(ctx interface{}, cmd interface{}) *MockCreateCampsiteHandler_Handle_Call {
	return &MockCreateCampsiteHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, cmd)}
}

func (_c *MockCreateCampsiteHandler_Handle_Call) Run(run func(ctx context.Context, cmd CreateCampsite)) *MockCreateCampsiteHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateCampsite
		if args[1] != nil {
			arg1 = args[1].(CreateCampsite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateCampsiteHandler_Handle_Call) Return(err error) *MockCreateCampsiteHandler_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreateCampsiteHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, cmd CreateCampsite) error) *MockCreateCampsiteHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}
