// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package command

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateBookingHandler creates a new instance of MockCreateBookingHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateBookingHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateBookingHandler {
	mock := &MockCreateBookingHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateBookingHandler is an autogenerated mock type for the CreateBookingHandler type
type MockCreateBookingHandler struct {
	mock.Mock
}

type MockCreateBookingHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateBookingHandler) EXPECT() *MockCreateBookingHandler_Expecter {
	return &MockCreateBookingHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockCreateBookingHandler
func (_mock *MockCreateBookingHandler) Handle(ctx context.Context, cmd CreateBooking) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateBooking) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreateBookingHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockCreateBookingHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd CreateBooking
func (_e *MockCreateBookingHandler_Expecter) Handle(ctx interface{}, cmd interface{}) *MockCreateBookingHandler_Handle_Call {
	return &MockCreateBookingHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, cmd)}
}

func (_c *MockCreateBookingHandler_Handle_Call) Run(run func(ctx context.Context, cmd CreateBooking)) *MockCreateBookingHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateBooking
		if args[1] != nil {
			arg1 = args[1].(CreateBooking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCreateBookingHandler_Handle_Call) Return(err error) *MockCreateBookingHandler_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreateBookingHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, cmd CreateBooking) error) *MockCreateBookingHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}
