// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package command

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCancelBookingHandler creates a new instance of MockCancelBookingHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCancelBookingHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCancelBookingHandler {
	mock := &MockCancelBookingHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCancelBookingHandler is an autogenerated mock type for the CancelBookingHandler type
type MockCancelBookingHandler struct {
	mock.Mock
}

type MockCancelBookingHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCancelBookingHandler) EXPECT() *MockCancelBookingHandler_Expecter {
	return &MockCancelBookingHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockCancelBookingHandler
func (_mock *MockCancelBookingHandler) Handle(ctx context.Context, cmd CancelBooking) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CancelBooking) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCancelBookingHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockCancelBookingHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd CancelBooking
func (_e *MockCancelBookingHandler_Expecter) Handle(ctx interface{}, cmd interface{}) *MockCancelBookingHandler_Handle_Call {
	return &MockCancelBookingHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, cmd)}
}

func (_c *MockCancelBookingHandler_Handle_Call) Run(run func(ctx context.Context, cmd CancelBooking)) *MockCancelBookingHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CancelBooking
		if args[1] != nil {
			arg1 = args[1].(CancelBooking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCancelBookingHandler_Handle_Call) Return(err error) *MockCancelBookingHandler_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCancelBookingHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, cmd CancelBooking) error) *MockCancelBookingHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}
