-- +goose Up
CREATE TABLE campgrounds.bookings
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id  varchar(255)                            NOT NULL,
    campsite_id varchar(255)                            NOT NULL REFERENCES campgrounds.campsites(campsite_id),
    email       varchar(50)                             NOT NULL,
    full_name   varchar(50)                             NOT NULL,
    start_date  date                                    NOT NULL,
    end_date    date                                    NOT NULL,
    active      boolean                                 NOT NULL,
    created_at  timestamptz                             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamptz                             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE UNIQUE INDEX unique_bookings_booking_id ON campgrounds.bookings (booking_id);

-- +goose Down
DROP TABLE IF EXISTS campgrounds.bookings;
