###
GRPC localhost:8085/campgroundspb.v1.CampgroundsService/GetCampsites

{}

<> 2024-05-23T152334.OK.json

###
GRPC localhost:8085/campgroundspb.v1.CampgroundsService/CreateCampsite

{
  "campsite_code": "CAMP09",
  "capacity": 12,
  "restrooms": true,
  "drinking_water": true,
  "picnic_table": true,
  "fire_pit": true
}