run:
  timeout: 10m

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
    disable:
      - fieldalignment

linters:
  disable-all: true
  enable:
    - typecheck # This is to improve error reporting
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - revive
    - exportloopref
    - staticcheck
    - unconvert
    - unused
    - misspell
    - makezero
    - whitespace
    - errcheck

issues:
  exclude-dirs:
    - readme
