CREATE TABLE campsites
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    campsite_id    VARCHAR(255)                            NOT NULL,
    campsite_code  VARCHAR(255)                            NOT NULL,
    capacity       INTEGER                                 NOT NULL,
    restrooms      BOOLEAN                                 NOT NULL,
    drinking_water BOOLEAN                                 NOT NULL,
    picnic_table   BOOLEAN                                 NOT NULL,
    fire_pit       BOOLEAN                                 NOT NULL,
    active         BOOLEAN                                 NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_campsites PRIMARY KEY (id)
);