// Code generated by mockery v2.43.2. DO NOT EDIT.

package waiter

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWaitFunc is an autogenerated mock type for the WaitFunc type
type MockWaitFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *MockWaitFunc) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWaitFunc creates a new instance of MockWaitFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWaitFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWaitFunc {
	mock := &MockWaitFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
