version: '3.9'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../docker/db:/docker-entrypoint-initdb.d/
