services:
  campgrounds:
    container_name: campgrounds
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../db/init:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U campgrounds_user -d campgrounds" ]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
