// Code generated by mockery v2.43.2. DO NOT EDIT.

package handler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQuery is an autogenerated mock type for the Query type
type MockQuery[Q interface{}, R interface{}] struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, qry
func (_m *MockQuery[Q, R]) Handle(ctx context.Context, qry Q) (R, error) {
	ret := _m.Called(ctx, qry)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 R
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Q) (R, error)); ok {
		return rf(ctx, qry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Q) R); ok {
		r0 = rf(ctx, qry)
	} else {
		r0 = ret.Get(0).(R)
	}

	if rf, ok := ret.Get(1).(func(context.Context, Q) error); ok {
		r1 = rf(ctx, qry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockQuery creates a new instance of MockQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuery[Q interface{}, R interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuery[Q, R] {
	mock := &MockQuery[Q, R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
