#!/bin/bash
set -e
echo "Creating campgrounds database..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE "$CAMPGROUNDS_DB";
  CREATE USER "$CAMPGROUNDS_USER" WITH ENCRYPTED PASSWORD '$CAMPGROUNDS_PASSWORD';
  ALTER DATABASE "$CAMPGROUNDS_DB" OWNER TO "$CAMPGROUNDS_USER";
  GRANT USAGE ON SCHEMA public TO "$CAMPGROUNDS_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$CAMPGROUNDS_DB" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS moddatetime;
EOSQL
