// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/bookingspb/v1/api.proto

package bookingspbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BookingsService_GetCampsites_FullMethodName   = "/bookingspb.v1.BookingsService/GetCampsites"
	BookingsService_GetBooking_FullMethodName     = "/bookingspb.v1.BookingsService/GetBooking"
	BookingsService_CreateBooking_FullMethodName  = "/bookingspb.v1.BookingsService/CreateBooking"
	BookingsService_UpdateBooking_FullMethodName  = "/bookingspb.v1.BookingsService/UpdateBooking"
	BookingsService_CancelBooking_FullMethodName  = "/bookingspb.v1.BookingsService/CancelBooking"
	BookingsService_GetVacantDates_FullMethodName = "/bookingspb.v1.BookingsService/GetVacantDates"
)

// BookingsServiceClient is the client API for BookingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingsServiceClient interface {
	GetCampsites(ctx context.Context, in *GetCampsitesRequest, opts ...grpc.CallOption) (*GetCampsitesResponse, error)
	GetBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*GetBookingResponse, error)
	CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error)
	UpdateBooking(ctx context.Context, in *UpdateBookingRequest, opts ...grpc.CallOption) (*UpdateBookingResponse, error)
	CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error)
	GetVacantDates(ctx context.Context, in *GetVacantDatesRequest, opts ...grpc.CallOption) (*GetVacantDatesResponse, error)
}

type bookingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingsServiceClient(cc grpc.ClientConnInterface) BookingsServiceClient {
	return &bookingsServiceClient{cc}
}

func (c *bookingsServiceClient) GetCampsites(ctx context.Context, in *GetCampsitesRequest, opts ...grpc.CallOption) (*GetCampsitesResponse, error) {
	out := new(GetCampsitesResponse)
	err := c.cc.Invoke(ctx, BookingsService_GetCampsites_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsServiceClient) GetBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*GetBookingResponse, error) {
	out := new(GetBookingResponse)
	err := c.cc.Invoke(ctx, BookingsService_GetBooking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsServiceClient) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error) {
	out := new(CreateBookingResponse)
	err := c.cc.Invoke(ctx, BookingsService_CreateBooking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsServiceClient) UpdateBooking(ctx context.Context, in *UpdateBookingRequest, opts ...grpc.CallOption) (*UpdateBookingResponse, error) {
	out := new(UpdateBookingResponse)
	err := c.cc.Invoke(ctx, BookingsService_UpdateBooking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsServiceClient) CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error) {
	out := new(CancelBookingResponse)
	err := c.cc.Invoke(ctx, BookingsService_CancelBooking_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingsServiceClient) GetVacantDates(ctx context.Context, in *GetVacantDatesRequest, opts ...grpc.CallOption) (*GetVacantDatesResponse, error) {
	out := new(GetVacantDatesResponse)
	err := c.cc.Invoke(ctx, BookingsService_GetVacantDates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingsServiceServer is the server API for BookingsService service.
// All implementations must embed UnimplementedBookingsServiceServer
// for forward compatibility
type BookingsServiceServer interface {
	GetCampsites(context.Context, *GetCampsitesRequest) (*GetCampsitesResponse, error)
	GetBooking(context.Context, *GetBookingRequest) (*GetBookingResponse, error)
	CreateBooking(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error)
	UpdateBooking(context.Context, *UpdateBookingRequest) (*UpdateBookingResponse, error)
	CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error)
	GetVacantDates(context.Context, *GetVacantDatesRequest) (*GetVacantDatesResponse, error)
	mustEmbedUnimplementedBookingsServiceServer()
}

// UnimplementedBookingsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookingsServiceServer struct {
}

func (UnimplementedBookingsServiceServer) GetCampsites(context.Context, *GetCampsitesRequest) (*GetCampsitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampsites not implemented")
}
func (UnimplementedBookingsServiceServer) GetBooking(context.Context, *GetBookingRequest) (*GetBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooking not implemented")
}
func (UnimplementedBookingsServiceServer) CreateBooking(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}
func (UnimplementedBookingsServiceServer) UpdateBooking(context.Context, *UpdateBookingRequest) (*UpdateBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBooking not implemented")
}
func (UnimplementedBookingsServiceServer) CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedBookingsServiceServer) GetVacantDates(context.Context, *GetVacantDatesRequest) (*GetVacantDatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacantDates not implemented")
}
func (UnimplementedBookingsServiceServer) mustEmbedUnimplementedBookingsServiceServer() {}

// UnsafeBookingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingsServiceServer will
// result in compilation errors.
type UnsafeBookingsServiceServer interface {
	mustEmbedUnimplementedBookingsServiceServer()
}

func RegisterBookingsServiceServer(s grpc.ServiceRegistrar, srv BookingsServiceServer) {
	s.RegisterService(&BookingsService_ServiceDesc, srv)
}

func _BookingsService_GetCampsites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampsitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).GetCampsites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingsService_GetCampsites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).GetCampsites(ctx, req.(*GetCampsitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingsService_GetBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).GetBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingsService_GetBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).GetBooking(ctx, req.(*GetBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingsService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingsService_CreateBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).CreateBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingsService_UpdateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).UpdateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingsService_UpdateBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).UpdateBooking(ctx, req.(*UpdateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingsService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingsService_CancelBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).CancelBooking(ctx, req.(*CancelBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingsService_GetVacantDates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacantDatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingsServiceServer).GetVacantDates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingsService_GetVacantDates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingsServiceServer).GetVacantDates(ctx, req.(*GetVacantDatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingsService_ServiceDesc is the grpc.ServiceDesc for BookingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bookingspb.v1.BookingsService",
	HandlerType: (*BookingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCampsites",
			Handler:    _BookingsService_GetCampsites_Handler,
		},
		{
			MethodName: "GetBooking",
			Handler:    _BookingsService_GetBooking_Handler,
		},
		{
			MethodName: "CreateBooking",
			Handler:    _BookingsService_CreateBooking_Handler,
		},
		{
			MethodName: "UpdateBooking",
			Handler:    _BookingsService_UpdateBooking_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _BookingsService_CancelBooking_Handler,
		},
		{
			MethodName: "GetVacantDates",
			Handler:    _BookingsService_GetVacantDates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bookingspb/v1/api.proto",
}
