primary:
  extraVolumes:
    - name: init-db-scripts
      configMap:
        name: init-db-config
  extraVolumeMounts:
    - name: init-db-scripts
      mountPath: /docker-entrypoint-initdb.d/
      readOnly: true
  persistence:
    enabled: true
    size: 4Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
