// Code generated by mockery v2.43.1. DO NOT EDIT.

package application

import (
	context "context"

	commands "github.com/igor-baiborodine/campsite-booking-go/internal/application/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockCommands is an autogenerated mock type for the Commands type
type MockCommands struct {
	mock.Mock
}

// CancelBooking provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CancelBooking(ctx context.Context, cmd commands.CancelBooking) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CancelBooking) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBooking provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CreateBooking(ctx context.Context, cmd commands.CreateBooking) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateBooking) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCampsite provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CreateCampsite(ctx context.Context, cmd commands.CreateCampsite) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateCampsite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateCampsite) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBooking provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) UpdateBooking(ctx context.Context, cmd commands.UpdateBooking) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.UpdateBooking) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCommands creates a new instance of MockCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommands {
	mock := &MockCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
