// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingValidator creates a new instance of MockBookingValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingValidator {
	mock := &MockBookingValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingValidator is an autogenerated mock type for the BookingValidator type
type MockBookingValidator struct {
	mock.Mock
}

type MockBookingValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingValidator) EXPECT() *MockBookingValidator_Expecter {
	return &MockBookingValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockBookingValidator
func (_mock *MockBookingValidator) Validate(b *Booking) error {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Booking) error); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockBookingValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - b *Booking
func (_e *MockBookingValidator_Expecter) Validate(b interface{}) *MockBookingValidator_Validate_Call {
	return &MockBookingValidator_Validate_Call{Call: _e.mock.On("Validate", b)}
}

func (_c *MockBookingValidator_Validate_Call) Run(run func(b *Booking)) *MockBookingValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Booking
		if args[0] != nil {
			arg0 = args[0].(*Booking)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingValidator_Validate_Call) Return(err error) *MockBookingValidator_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingValidator_Validate_Call) RunAndReturn(run func(b *Booking) error) *MockBookingValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
