// Code generated by mockery v2.43.2. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockBookingValidator is an autogenerated mock type for the BookingValidator type
type MockBookingValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: b
func (_m *MockBookingValidator) Validate(b *Booking) error {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Booking) error); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBookingValidator creates a new instance of MockBookingValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingValidator {
	mock := &MockBookingValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
