// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: campgroundspb/v1/api.proto

package campgroundspbv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCampsitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampsitesRequest) Reset() {
	*x = GetCampsitesRequest{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampsitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampsitesRequest) ProtoMessage() {}

func (x *GetCampsitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampsitesRequest.ProtoReflect.Descriptor instead.
func (*GetCampsitesRequest) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{0}
}

type GetCampsitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campsites     []*Campsite            `protobuf:"bytes,1,rep,name=campsites,proto3" json:"campsites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampsitesResponse) Reset() {
	*x = GetCampsitesResponse{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampsitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampsitesResponse) ProtoMessage() {}

func (x *GetCampsitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampsitesResponse.ProtoReflect.Descriptor instead.
func (*GetCampsitesResponse) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetCampsitesResponse) GetCampsites() []*Campsite {
	if x != nil {
		return x.Campsites
	}
	return nil
}

type CreateCampsiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampsiteCode  string                 `protobuf:"bytes,1,opt,name=campsite_code,json=campsiteCode,proto3" json:"campsite_code,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	DrinkingWater bool                   `protobuf:"varint,3,opt,name=drinking_water,json=drinkingWater,proto3" json:"drinking_water,omitempty"`
	Restrooms     bool                   `protobuf:"varint,4,opt,name=restrooms,proto3" json:"restrooms,omitempty"`
	PicnicTable   bool                   `protobuf:"varint,5,opt,name=picnic_table,json=picnicTable,proto3" json:"picnic_table,omitempty"`
	FirePit       bool                   `protobuf:"varint,6,opt,name=fire_pit,json=firePit,proto3" json:"fire_pit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampsiteRequest) Reset() {
	*x = CreateCampsiteRequest{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampsiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampsiteRequest) ProtoMessage() {}

func (x *CreateCampsiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampsiteRequest.ProtoReflect.Descriptor instead.
func (*CreateCampsiteRequest) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCampsiteRequest) GetCampsiteCode() string {
	if x != nil {
		return x.CampsiteCode
	}
	return ""
}

func (x *CreateCampsiteRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateCampsiteRequest) GetDrinkingWater() bool {
	if x != nil {
		return x.DrinkingWater
	}
	return false
}

func (x *CreateCampsiteRequest) GetRestrooms() bool {
	if x != nil {
		return x.Restrooms
	}
	return false
}

func (x *CreateCampsiteRequest) GetPicnicTable() bool {
	if x != nil {
		return x.PicnicTable
	}
	return false
}

func (x *CreateCampsiteRequest) GetFirePit() bool {
	if x != nil {
		return x.FirePit
	}
	return false
}

type CreateCampsiteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampsiteId    string                 `protobuf:"bytes,1,opt,name=campsite_id,json=campsiteId,proto3" json:"campsite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampsiteResponse) Reset() {
	*x = CreateCampsiteResponse{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampsiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampsiteResponse) ProtoMessage() {}

func (x *CreateCampsiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampsiteResponse.ProtoReflect.Descriptor instead.
func (*CreateCampsiteResponse) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCampsiteResponse) GetCampsiteId() string {
	if x != nil {
		return x.CampsiteId
	}
	return ""
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type GetBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingResponse) Reset() {
	*x = GetBookingResponse{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingResponse) ProtoMessage() {}

func (x *GetBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingResponse.ProtoReflect.Descriptor instead.
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampsiteId    string                 `protobuf:"bytes,1,opt,name=campsite_id,json=campsiteId,proto3" json:"campsite_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBookingRequest) GetCampsiteId() string {
	if x != nil {
		return x.CampsiteId
	}
	return ""
}

func (x *CreateBookingRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateBookingRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateBookingRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateBookingRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type UpdateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingRequest) Reset() {
	*x = UpdateBookingRequest{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingRequest) ProtoMessage() {}

func (x *UpdateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingRequest) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBookingRequest) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type UpdateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingResponse) Reset() {
	*x = UpdateBookingResponse{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingResponse) ProtoMessage() {}

func (x *UpdateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookingResponse) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{9}
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{11}
}

type GetVacantDatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampsiteId    string                 `protobuf:"bytes,1,opt,name=campsite_id,json=campsiteId,proto3" json:"campsite_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacantDatesRequest) Reset() {
	*x = GetVacantDatesRequest{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacantDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacantDatesRequest) ProtoMessage() {}

func (x *GetVacantDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacantDatesRequest.ProtoReflect.Descriptor instead.
func (*GetVacantDatesRequest) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetVacantDatesRequest) GetCampsiteId() string {
	if x != nil {
		return x.CampsiteId
	}
	return ""
}

func (x *GetVacantDatesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetVacantDatesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetVacantDatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacantDates   []string               `protobuf:"bytes,1,rep,name=vacant_dates,json=vacantDates,proto3" json:"vacant_dates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacantDatesResponse) Reset() {
	*x = GetVacantDatesResponse{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacantDatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacantDatesResponse) ProtoMessage() {}

func (x *GetVacantDatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacantDatesResponse.ProtoReflect.Descriptor instead.
func (*GetVacantDatesResponse) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetVacantDatesResponse) GetVacantDates() []string {
	if x != nil {
		return x.VacantDates
	}
	return nil
}

type Campsite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of campsite, must be in UUID format.
	CampsiteId string `protobuf:"bytes,1,opt,name=campsite_id,json=campsiteId,proto3" json:"campsite_id,omitempty"`
	// Unique code of campsite.
	CampsiteCode string `protobuf:"bytes,2,opt,name=campsite_code,json=campsiteCode,proto3" json:"campsite_code,omitempty"`
	// Maximum number of people campsite can accommodate.
	Capacity int32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Indicates if campsite has drinking water.
	DrinkingWater bool `protobuf:"varint,4,opt,name=drinking_water,json=drinkingWater,proto3" json:"drinking_water,omitempty"`
	// Indicates if campsite has restrooms.
	Restrooms bool `protobuf:"varint,5,opt,name=restrooms,proto3" json:"restrooms,omitempty"`
	// Indicates if campsite has a picnic table.
	PicnicTable bool `protobuf:"varint,6,opt,name=picnic_table,json=picnicTable,proto3" json:"picnic_table,omitempty"`
	// Indicates if campsite has a fire pit.
	FirePit bool `protobuf:"varint,7,opt,name=fire_pit,json=firePit,proto3" json:"fire_pit,omitempty"`
	// Indicates if campsite is active.
	Active        bool `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campsite) Reset() {
	*x = Campsite{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campsite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campsite) ProtoMessage() {}

func (x *Campsite) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campsite.ProtoReflect.Descriptor instead.
func (*Campsite) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{14}
}

func (x *Campsite) GetCampsiteId() string {
	if x != nil {
		return x.CampsiteId
	}
	return ""
}

func (x *Campsite) GetCampsiteCode() string {
	if x != nil {
		return x.CampsiteCode
	}
	return ""
}

func (x *Campsite) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Campsite) GetDrinkingWater() bool {
	if x != nil {
		return x.DrinkingWater
	}
	return false
}

func (x *Campsite) GetRestrooms() bool {
	if x != nil {
		return x.Restrooms
	}
	return false
}

func (x *Campsite) GetPicnicTable() bool {
	if x != nil {
		return x.PicnicTable
	}
	return false
}

func (x *Campsite) GetFirePit() bool {
	if x != nil {
		return x.FirePit
	}
	return false
}

func (x *Campsite) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Booking struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of booking, must be in UUID format.
	BookingId string `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	// Identifier of the campsite booked, must be in UUID format.
	CampsiteId string `protobuf:"bytes,2,opt,name=campsite_id,json=campsiteId,proto3" json:"campsite_id,omitempty"`
	// Email of person who made booking.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Full name of person who made booking.
	FullName string `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// Start date of booking, must be in ISO-8601 format (YYYY-MM-DD).
	StartDate string `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// End date of booking, must be in ISO-8601 format (YYYY-MM-DD).
	EndDate string `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// Indicates if booking is active.
	Active bool `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	// Version of booking.
	Version       int64 `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_campgroundspb_v1_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_campgroundspb_v1_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_campgroundspb_v1_api_proto_rawDescGZIP(), []int{15}
}

func (x *Booking) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *Booking) GetCampsiteId() string {
	if x != nil {
		return x.CampsiteId
	}
	return ""
}

func (x *Booking) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Booking) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Booking) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Booking) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Booking) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Booking) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_campgroundspb_v1_api_proto protoreflect.FileDescriptor

const file_campgroundspb_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x1acampgroundspb/v1/api.proto\x12\x10campgroundspb.v1\x1a\x1bbuf/validate/validate.proto\"\x15\n" +
	"\x13GetCampsitesRequest\"P\n" +
	"\x14GetCampsitesResponse\x128\n" +
	"\tcampsites\x18\x01 \x03(\v2\x1a.campgroundspb.v1.CampsiteR\tcampsites\"\xed\x01\n" +
	"\x15CreateCampsiteRequest\x12,\n" +
	"\rcampsite_code\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fcampsiteCode\x12#\n" +
	"\bcapacity\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bcapacity\x12%\n" +
	"\x0edrinking_water\x18\x03 \x01(\bR\rdrinkingWater\x12\x1c\n" +
	"\trestrooms\x18\x04 \x01(\bR\trestrooms\x12!\n" +
	"\fpicnic_table\x18\x05 \x01(\bR\vpicnicTable\x12\x19\n" +
	"\bfire_pit\x18\x06 \x01(\bR\afirePit\"9\n" +
	"\x16CreateCampsiteResponse\x12\x1f\n" +
	"\vcampsite_id\x18\x01 \x01(\tR\n" +
	"campsiteId\"<\n" +
	"\x11GetBookingRequest\x12'\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tbookingId\"I\n" +
	"\x12GetBookingResponse\x123\n" +
	"\abooking\x18\x01 \x01(\v2\x19.campgroundspb.v1.BookingR\abooking\"\xb6\x02\n" +
	"\x14CreateBookingRequest\x12)\n" +
	"\vcampsite_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"campsiteId\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12$\n" +
	"\tfull_name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bfullName\x12X\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tB9\xbaH6r422^\\d{4}-([0][1-9]|1[0-2])-([0][1-9]|[1-2]\\d|3[01])$R\tstartDate\x12T\n" +
	"\bend_date\x18\x05 \x01(\tB9\xbaH6r422^\\d{4}-([0][1-9]|1[0-2])-([0][1-9]|[1-2]\\d|3[01])$R\aendDate\"6\n" +
	"\x15CreateBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"K\n" +
	"\x14UpdateBookingRequest\x123\n" +
	"\abooking\x18\x01 \x01(\v2\x19.campgroundspb.v1.BookingR\abooking\"\x17\n" +
	"\x15UpdateBookingResponse\"?\n" +
	"\x14CancelBookingRequest\x12'\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tbookingId\"\x17\n" +
	"\x15CancelBookingResponse\"\xf2\x01\n" +
	"\x15GetVacantDatesRequest\x12)\n" +
	"\vcampsite_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"campsiteId\x12X\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tB9\xbaH6r422^\\d{4}-([0][1-9]|1[0-2])-([0][1-9]|[1-2]\\d|3[01])$R\tstartDate\x12T\n" +
	"\bend_date\x18\x03 \x01(\tB9\xbaH6r422^\\d{4}-([0][1-9]|1[0-2])-([0][1-9]|[1-2]\\d|3[01])$R\aendDate\";\n" +
	"\x16GetVacantDatesResponse\x12!\n" +
	"\fvacant_dates\x18\x01 \x03(\tR\vvacantDates\"\xa3\x02\n" +
	"\bCampsite\x12)\n" +
	"\vcampsite_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"campsiteId\x12,\n" +
	"\rcampsite_code\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fcampsiteCode\x12#\n" +
	"\bcapacity\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bcapacity\x12%\n" +
	"\x0edrinking_water\x18\x04 \x01(\bR\rdrinkingWater\x12\x1c\n" +
	"\trestrooms\x18\x05 \x01(\bR\trestrooms\x12!\n" +
	"\fpicnic_table\x18\x06 \x01(\bR\vpicnicTable\x12\x19\n" +
	"\bfire_pit\x18\a \x01(\bR\afirePit\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\"\x8d\x03\n" +
	"\aBooking\x12'\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tbookingId\x12)\n" +
	"\vcampsite_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"campsiteId\x12\x1d\n" +
	"\x05email\x18\x03 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12$\n" +
	"\tfull_name\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bfullName\x12X\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tB9\xbaH6r422^\\d{4}-([0][1-9]|1[0-2])-([0][1-9]|[1-2]\\d|3[01])$R\tstartDate\x12T\n" +
	"\bend_date\x18\x06 \x01(\tB9\xbaH6r422^\\d{4}-([0][1-9]|1[0-2])-([0][1-9]|[1-2]\\d|3[01])$R\aendDate\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12!\n" +
	"\aversion\x18\t \x01(\x03B\a\xbaH\x04\"\x02 \x00R\aversion2\xca\x05\n" +
	"\x12CampgroundsService\x12_\n" +
	"\fGetCampsites\x12%.campgroundspb.v1.GetCampsitesRequest\x1a&.campgroundspb.v1.GetCampsitesResponse\"\x00\x12e\n" +
	"\x0eCreateCampsite\x12'.campgroundspb.v1.CreateCampsiteRequest\x1a(.campgroundspb.v1.CreateCampsiteResponse\"\x00\x12Y\n" +
	"\n" +
	"GetBooking\x12#.campgroundspb.v1.GetBookingRequest\x1a$.campgroundspb.v1.GetBookingResponse\"\x00\x12b\n" +
	"\rCreateBooking\x12&.campgroundspb.v1.CreateBookingRequest\x1a'.campgroundspb.v1.CreateBookingResponse\"\x00\x12b\n" +
	"\rUpdateBooking\x12&.campgroundspb.v1.UpdateBookingRequest\x1a'.campgroundspb.v1.UpdateBookingResponse\"\x00\x12b\n" +
	"\rCancelBooking\x12&.campgroundspb.v1.CancelBookingRequest\x1a'.campgroundspb.v1.CancelBookingResponse\"\x00\x12e\n" +
	"\x0eGetVacantDates\x12'.campgroundspb.v1.GetVacantDatesRequest\x1a(.campgroundspb.v1.GetVacantDatesResponse\"\x00B\xa3\x01\n" +
	"\x14com.campgroundspb.v1B\bApiProtoP\x01Z campgroundspb/v1;campgroundspbv1\xa2\x02\x03CXX\xaa\x02\x10Campgroundspb.V1\xca\x02\x10Campgroundspb\\V1\xe2\x02\x1cCampgroundspb\\V1\\GPBMetadata\xea\x02\x11Campgroundspb::V1b\x06proto3"

var (
	file_campgroundspb_v1_api_proto_rawDescOnce sync.Once
	file_campgroundspb_v1_api_proto_rawDescData []byte
)

func file_campgroundspb_v1_api_proto_rawDescGZIP() []byte {
	file_campgroundspb_v1_api_proto_rawDescOnce.Do(func() {
		file_campgroundspb_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_campgroundspb_v1_api_proto_rawDesc), len(file_campgroundspb_v1_api_proto_rawDesc)))
	})
	return file_campgroundspb_v1_api_proto_rawDescData
}

var file_campgroundspb_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_campgroundspb_v1_api_proto_goTypes = []any{
	(*GetCampsitesRequest)(nil),    // 0: campgroundspb.v1.GetCampsitesRequest
	(*GetCampsitesResponse)(nil),   // 1: campgroundspb.v1.GetCampsitesResponse
	(*CreateCampsiteRequest)(nil),  // 2: campgroundspb.v1.CreateCampsiteRequest
	(*CreateCampsiteResponse)(nil), // 3: campgroundspb.v1.CreateCampsiteResponse
	(*GetBookingRequest)(nil),      // 4: campgroundspb.v1.GetBookingRequest
	(*GetBookingResponse)(nil),     // 5: campgroundspb.v1.GetBookingResponse
	(*CreateBookingRequest)(nil),   // 6: campgroundspb.v1.CreateBookingRequest
	(*CreateBookingResponse)(nil),  // 7: campgroundspb.v1.CreateBookingResponse
	(*UpdateBookingRequest)(nil),   // 8: campgroundspb.v1.UpdateBookingRequest
	(*UpdateBookingResponse)(nil),  // 9: campgroundspb.v1.UpdateBookingResponse
	(*CancelBookingRequest)(nil),   // 10: campgroundspb.v1.CancelBookingRequest
	(*CancelBookingResponse)(nil),  // 11: campgroundspb.v1.CancelBookingResponse
	(*GetVacantDatesRequest)(nil),  // 12: campgroundspb.v1.GetVacantDatesRequest
	(*GetVacantDatesResponse)(nil), // 13: campgroundspb.v1.GetVacantDatesResponse
	(*Campsite)(nil),               // 14: campgroundspb.v1.Campsite
	(*Booking)(nil),                // 15: campgroundspb.v1.Booking
}
var file_campgroundspb_v1_api_proto_depIdxs = []int32{
	14, // 0: campgroundspb.v1.GetCampsitesResponse.campsites:type_name -> campgroundspb.v1.Campsite
	15, // 1: campgroundspb.v1.GetBookingResponse.booking:type_name -> campgroundspb.v1.Booking
	15, // 2: campgroundspb.v1.UpdateBookingRequest.booking:type_name -> campgroundspb.v1.Booking
	0,  // 3: campgroundspb.v1.CampgroundsService.GetCampsites:input_type -> campgroundspb.v1.GetCampsitesRequest
	2,  // 4: campgroundspb.v1.CampgroundsService.CreateCampsite:input_type -> campgroundspb.v1.CreateCampsiteRequest
	4,  // 5: campgroundspb.v1.CampgroundsService.GetBooking:input_type -> campgroundspb.v1.GetBookingRequest
	6,  // 6: campgroundspb.v1.CampgroundsService.CreateBooking:input_type -> campgroundspb.v1.CreateBookingRequest
	8,  // 7: campgroundspb.v1.CampgroundsService.UpdateBooking:input_type -> campgroundspb.v1.UpdateBookingRequest
	10, // 8: campgroundspb.v1.CampgroundsService.CancelBooking:input_type -> campgroundspb.v1.CancelBookingRequest
	12, // 9: campgroundspb.v1.CampgroundsService.GetVacantDates:input_type -> campgroundspb.v1.GetVacantDatesRequest
	1,  // 10: campgroundspb.v1.CampgroundsService.GetCampsites:output_type -> campgroundspb.v1.GetCampsitesResponse
	3,  // 11: campgroundspb.v1.CampgroundsService.CreateCampsite:output_type -> campgroundspb.v1.CreateCampsiteResponse
	5,  // 12: campgroundspb.v1.CampgroundsService.GetBooking:output_type -> campgroundspb.v1.GetBookingResponse
	7,  // 13: campgroundspb.v1.CampgroundsService.CreateBooking:output_type -> campgroundspb.v1.CreateBookingResponse
	9,  // 14: campgroundspb.v1.CampgroundsService.UpdateBooking:output_type -> campgroundspb.v1.UpdateBookingResponse
	11, // 15: campgroundspb.v1.CampgroundsService.CancelBooking:output_type -> campgroundspb.v1.CancelBookingResponse
	13, // 16: campgroundspb.v1.CampgroundsService.GetVacantDates:output_type -> campgroundspb.v1.GetVacantDatesResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_campgroundspb_v1_api_proto_init() }
func file_campgroundspb_v1_api_proto_init() {
	if File_campgroundspb_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_campgroundspb_v1_api_proto_rawDesc), len(file_campgroundspb_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campgroundspb_v1_api_proto_goTypes,
		DependencyIndexes: file_campgroundspb_v1_api_proto_depIdxs,
		MessageInfos:      file_campgroundspb_v1_api_proto_msgTypes,
	}.Build()
	File_campgroundspb_v1_api_proto = out.File
	file_campgroundspb_v1_api_proto_goTypes = nil
	file_campgroundspb_v1_api_proto_depIdxs = nil
}
