name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ["stable", "oldstable"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Install tools
        run: make install-tools

      - name: Mod tidy
        run: make mod-tidy-diff

      - name: Mod download
        run: make mod-download

      - name: Mod verify
        run: make mod-verify

      - name: Generate
        run: make generate-diff

      - name: Format
        run: make format-diff

      - name: Build
        run: make build

      - name: Unit tests
        run: make unit-tests

      - name: Integration tests
        run: make integration-tests
