name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        go: ["stable", "oldstable"]
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        check-latest: true

    - name: Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Tidy
      run: go mod tidy && git diff --exit-code

    - name: Download
      run: go mod download

    - name: Verify
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Unit tests
      run: go test -v ./...

    - name: Integration tests
      run: go test ./... -tags integration  
