name: Generate README TOC

on:
  push:
    branches: [ "master" ]
    paths: [ "readme/*.md" ]

jobs:
  generate-toc:
    name: Generate TOC
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: "readme/*.md"
