name: readme-toc

on:
  push:
    branches: [ "main" ]
    paths: [ "docs/**/*.md" ]
  workflow_dispatch:

jobs:
  generate-toc:
    name: Generate TOC
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: "docs/**/*.md"
