apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    node:
      id: envoy-proxy
      cluster: grpc_cluster
    
    static_resources:
      listeners:
        - name: listener_grpc
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: listener_http
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                    route_config:
                      name: route
                      virtual_hosts:
                        - name: vh
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: /campgroundspb.v1.CampgroundsService
                                grpc: {}
                              route:
                                cluster: grpc_cluster
      clusters:
        - name: grpc_cluster
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: grpc_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "campgrounds.default.svc.cluster.local"
                          port_value: 8085

    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
